export const APIConfig = {
  API: {
    getAllContext: "v1/contexts",
    createContext: "v1/contexts",
    getContextById: "v1/contexts/id/",
    getContextValueById: "v1/contextvalues/",
    getContextValueByIdUnpaged: "v1/contextvalues/workspace/",
    checkContextName: "v1/contexts/check/", //is it inside a group?what about code?
    checkContextValue: "v1/contextvalues/check/", //what about code?/admin/api/v1/contextvalues/check/{contextId}/{name}
    getContextDescription:"v1/descriptions/contexts/id/",
    searchContext: "v1/contexts/search/",
    updateContext: "v1/contexts",
    updateContextValue: "v1/contextvalues",
    deleteContext: "v1/contexts/id/",
    getContextValueForEdit: "v1/contextvalues/id/",
    deleteContextValue: "v1/contextvalues/id/",
    getContextWithChild: "v1/contexts/child",
    searchContextWithChild:"v1/contexts/child/search/",
    getContextForHierarchy: "v1/contexts/hierarchy",
    getContextForHierarchyByGroupId: "v1/contexts/hierarchy/",
    getContextValueForHierarchy: "v1/contextvalues/hierarchy/",
    getContextValueForHierarchyExceptSelected: "v1/contextvalues/hierarchy/",
    getChildContextValuesForParent: "v1/contextvalues/workspace/",
    createModule: "v1/modules",
    getAllModules: "v1/modules",
    createBusinessComponent: "v1/businesscomponents",
    getAllBusinessComponents: "v1/businesscomponents",
    getModule: "v1/modules/id/",
    updateModule: "v1/modules",
    deleteModule: "v1/modules/id/",
    checkModule: "v1/modules/check/",
    getBusinessComponent: "v1/businesscomponents/id/",
    updateBusinessComponent: "v1/businesscomponents",
    deleteBusinessComponent: "v1/businesscomponents/id/",
    searchBusinessComponent: "v1/businesscomponents/search/",
    createHierarchy: "v1/hierarchies",
    getHierarchies: "v1/hierarchies",
    getHierarchyByID: "v1/hierarchies/id/",
    updateModuleHierarchy: "v1/hierarchies",
    getHierarchiesForBusinessComponent: "v1/hierarchies/businesscomponent",
    getLeastModulesForBusinessComponent:
      "v1/hierarchyrelations/businesscomponent/",
    checkBusinessComponent: "v1/businesscomponents/check/",
    createHierarchyRelations: "v1/hierarchyrelations",
    deleteHierarchy: "v1/hierarchies/id/",
    searchModule: "v1/modules/search/",
    getModuleToCreateHierarchy: "v1/modules/hierarchy",
    getModuleToCreateHierarchyRelation: "v1/modules/hierarchy/",
    deleteHierarchyRelation: "v1/hierarchyrelations/id/",
    searchModuleToCreateHierarchy: "v1/modules/hierarchy/search/",
    searchModuleToCreateHierarchyRelation: "v1/modules/hierarchy/search/",
    searchHierarchies: "v1/hierarchies/search/",
    //business relation type
    createRelationType: "v1/relationtypes",
    updateRelationType: "v1/relationtypes",
    deleteRelationType: "v1/relationtypes/id/",
    getAllRelationType: "v1/relationtypes",
    getRelationTypeById: "v1/relationtypes/id/",
    searchRelationType: "v1/relationtypes/search/",
    getAllContextGroups: "v1/contextgroups",
    getAllContextGroupsForDropdown: "v1/contextgroups/contexts",

    createContextGroup: "v1/contextgroups",
    updateContextGroup: "v1/contextgroups",
    deleteContextGroup: "v1/contextgroups/id/",
    checkContextGroupName: "v1/contextgroups/check/",
    searchContextGroupName:"v1/contextgroups/search/",
    getContextGroupById:"v1/contextgroups/id/",
    checkTopLevelModule: 'v1/modules/check/hierarchy/',
    addBulkBusinessComponents: 'v1/hierarchyrelations/bulk',

    // business component  relation 
    getModulesForBusinessComponents: 'v1/hierarchyrelations/businesscomponentrelations/',
    getChildForBusinessComponents: 'v1/hierarchyrelations/businesscomponentrelations/child/',
    createBusinessComponentRelation: 'v1/businesscomponentrelations',
    getAllBusinessComponentRelation: 'v1/businesscomponentrelations',
    getAllBusinessRelation: 'v1/businesscomponentrelations',
    searchBusinessRelation: 'v1/businesscomponentrelations/search/',
    deleteBusinessRelation: 'v1/businesscomponentrelations/id/',

    //Description API
    getModuleDescription : 'v1/descriptions/modules/id/',
    getBusinessComponentsDescription : 'v1/descriptions/businesscomponents/id/',

  },
};
